"""initial schema

Revision ID: a5d3bd521621
Revises: 
Create Date: 2026-09-18 17:55:04.760845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d3bd521621'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_table('connector_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_instances_organization_id'), 'connector_instances', ['organization_id'], unique=False)
    op.create_table('database_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dialect', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('encrypted_password', sa.String(length=500), nullable=False),
    sa.Column('source_query', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=500), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_connections_organization_id'), 'database_connections', ['organization_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('job_role', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('years_at_company', sa.Float(), nullable=True),
    sa.Column('job_satisfaction', sa.Float(), nullable=True),
    sa.Column('environment_satisfaction', sa.Float(), nullable=True),
    sa.Column('job_involvement', sa.Float(), nullable=True),
    sa.Column('years_since_last_promotion', sa.Float(), nullable=True),
    sa.Column('performance_rating_actual', sa.Float(), nullable=True),
    sa.Column('attrition_actual', sa.Boolean(), nullable=True),
    sa.Column('attrition_risk_score', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_external_ref'), 'employees', ['external_ref'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(length=50), nullable=False),
    sa.Column('machine_type', sa.String(length=10), nullable=False),
    sa.Column('air_temp_k', sa.Float(), nullable=True),
    sa.Column('process_temp_k', sa.Float(), nullable=True),
    sa.Column('rotational_speed_rpm', sa.Float(), nullable=True),
    sa.Column('torque_nm', sa.Float(), nullable=True),
    sa.Column('tool_wear_min', sa.Float(), nullable=True),
    sa.Column('extra_readings', sa.JSON(), nullable=False),
    sa.Column('actual_failure', sa.Boolean(), nullable=True),
    sa.Column('failure_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_label', sa.String(length=20), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_external_ref'), 'equipment', ['external_ref'], unique=False)
    op.create_index(op.f('ix_equipment_organization_id'), 'equipment', ['organization_id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('mape', sa.Float(), nullable=False),
    sa.Column('forecast_points', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_results_organization_id'), 'forecast_results', ['organization_id'], unique=False)
    op.create_table('fraud_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('actual_is_fraud', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_label', sa.String(length=20), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_transactions_external_ref'), 'fraud_transactions', ['external_ref'], unique=False)
    op.create_index(op.f('ix_fraud_transactions_organization_id'), 'fraud_transactions', ['organization_id'], unique=False)
    op.create_table('kpi_weight_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'department', 'kpi_name')
    )
    op.create_index(op.f('ix_kpi_weight_configs_department'), 'kpi_weight_configs', ['department'], unique=False)
    op.create_index(op.f('ix_kpi_weight_configs_organization_id'), 'kpi_weight_configs', ['organization_id'], unique=False)
    op.create_table('model_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('train_rows', sa.Integer(), nullable=False),
    sa.Column('test_rows', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_evaluations_module_key'), 'model_evaluations', ['module_key'], unique=False)
    op.create_index(op.f('ix_model_evaluations_organization_id'), 'model_evaluations', ['organization_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('feature_columns', sa.JSON(), nullable=False),
    sa.Column('training_reference_stats', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_module_key'), 'model_versions', ['module_key'], unique=False)
    op.create_index(op.f('ix_model_versions_organization_id'), 'model_versions', ['organization_id'], unique=False)
    op.create_table('module_enablements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'module_key')
    )
    op.create_index(op.f('ix_module_enablements_organization_id'), 'module_enablements', ['organization_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_table('usage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'module_key', 'day')
    )
    op.create_index(op.f('ix_usage_metrics_day'), 'usage_metrics', ['day'], unique=False)
    op.create_index(op.f('ix_usage_metrics_module_key'), 'usage_metrics', ['module_key'], unique=False)
    op.create_index(op.f('ix_usage_metrics_organization_id'), 'usage_metrics', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'org_admin', 'manager', 'employee', name='roleenum'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('encrypted_secret', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_received_at', sa.DateTime(), nullable=True),
    sa.Column('receive_count', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_organization_id'), 'webhook_endpoints', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_token'), 'webhook_endpoints', ['token'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('source_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_logs_organization_id'), 'chat_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chat_logs_user_id'), 'chat_logs', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_employee_id'), 'goals', ['employee_id'], unique=False)
    op.create_index(op.f('ix_goals_organization_id'), 'goals', ['organization_id'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('supplier_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_snapshots_organization_id'), 'inventory_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_product_id'), 'inventory_snapshots', ['product_id'], unique=False)
    op.create_table('performance_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('main_improvement_area', sa.String(length=100), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_scores_employee_id'), 'performance_scores', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_scores_organization_id'), 'performance_scores', ['organization_id'], unique=False)
    op.create_table('reorder_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_demand', sa.Float(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('recommended_order_qty', sa.Float(), nullable=False),
    sa.Column('stockout_probability', sa.Float(), nullable=False),
    sa.Column('risk_label', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reorder_recommendations_organization_id'), 'reorder_recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reorder_recommendations_product_id'), 'reorder_recommendations', ['product_id'], unique=False)
    op.create_table('sales_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('customer_ref', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_transactions_organization_id'), 'sales_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sales_transactions_product_id'), 'sales_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_transactions_transaction_date'), 'sales_transactions', ['transaction_date'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_organization_id'), 'scheduled_jobs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_jobs_organization_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_sales_transactions_transaction_date'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_product_id'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_organization_id'), table_name='sales_transactions')
    op.drop_table('sales_transactions')
    op.drop_index(op.f('ix_reorder_recommendations_product_id'), table_name='reorder_recommendations')
    op.drop_index(op.f('ix_reorder_recommendations_organization_id'), table_name='reorder_recommendations')
    op.drop_table('reorder_recommendations')
    op.drop_index(op.f('ix_performance_scores_organization_id'), table_name='performance_scores')
    op.drop_index(op.f('ix_performance_scores_employee_id'), table_name='performance_scores')
    op.drop_table('performance_scores')
    op.drop_index(op.f('ix_inventory_snapshots_product_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_organization_id'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_goals_organization_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_employee_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_chat_logs_user_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_organization_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_webhook_endpoints_token'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_organization_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_metrics_organization_id'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_module_key'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_day'), table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_module_enablements_organization_id'), table_name='module_enablements')
    op.drop_table('module_enablements')
    op.drop_index(op.f('ix_model_versions_organization_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_module_key'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_model_evaluations_organization_id'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_module_key'), table_name='model_evaluations')
    op.drop_table('model_evaluations')
    op.drop_index(op.f('ix_kpi_weight_configs_organization_id'), table_name='kpi_weight_configs')
    op.drop_index(op.f('ix_kpi_weight_configs_department'), table_name='kpi_weight_configs')
    op.drop_table('kpi_weight_configs')
    op.drop_index(op.f('ix_fraud_transactions_organization_id'), table_name='fraud_transactions')
    op.drop_index(op.f('ix_fraud_transactions_external_ref'), table_name='fraud_transactions')
    op.drop_table('fraud_transactions')
    op.drop_index(op.f('ix_forecast_results_organization_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_equipment_organization_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_external_ref'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_external_ref'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_database_connections_organization_id'), table_name='database_connections')
    op.drop_table('database_connections')
    op.drop_index(op.f('ix_connector_instances_organization_id'), table_name='connector_instances')
    op.drop_table('connector_instances')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('organizations')
    # ### end Alembic commands ###
